version: '3'

services:
  server:
    image: python-server
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: python-server
    ports:
      - "8080:8080"
    networks:
      - app_network

  nginx:
    image: reverse-proxy
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile   
    container_name: reverse-proxy
    depends_on:
      - server    
    environment: 
      - FORWARD_HOST=server
      - FORWARD_PORT=80
      - BASIC_USERNAME=manuela.nenganga
      - BASIC_PASSWORD=topsecret   
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - app_network      

networks:
  app_network:
    driver: bridge
